### ISSUE TITLE
Dismiss on background tap

### ISSUE THREAD

**Issue by xzenon** [JonasGessner/JGActionSheet#1]
Thanks for amazing action sheet!
One question - is it possible to somehow enable sheet dismissing by tapping not only some button but background also?

**Comment by JonasGessner** [comment]
This is what `outsidePressBlock` is for. See JGActionSheet.h

**Comment by xzenon** [comment]
Ahh, don't know how I missed that.
Thanks a lot for quick response!

**Comment by JonasGessner** [comment]
Also check out how it is implemented the example project!

**Comment by xzenon** [comment]
I see, outsidePressBlock is set only for iPad in example project and I was testing on iPhone - that's why I   missed it. Will read code carefully :)
