### ISSUE TITLE
Actionview doesnt start from top. 

### ISSUE THREAD

**Issue by josher8** [JonasGessner/JGActionSheet#10]
When you have a lot of actions and it opens, it doesnt start from the top to show the title first. It starts from the middle. Is there a way to fix this? Attached is a screenshot:. 
![screenshot 2015-01-21 10 02 32](https://cloud.githubusercontent.com/assets/1927750/5839549/b9bd6a92-a154-11e4-9292-caaedfc7d498.png)

**Comment by JonasGessner** [comment]
Not a bug, you're just showing the action sheet from the wrong view. You have to show it from the UINavigationController's view.

**Comment by josher8** [comment]
I even added all the buttons to your example app, and it did the same thing. Like it starts in the middle, but i can scroll up to the top.

**Comment by josher8** [comment]
http://recordit.co/4g9VkiV1nV

**Comment by JonasGessner** [comment]
Thats the preferred behavior, the status bar is kept visible. You should read the JGActionSheet.h file carefully, it has a 'insets' property and the example app sets the insets to (20, 0, 0, 0), thats why the status bar is kept visible.

**Comment by josher8** [comment]
Right, the status bar should show, but shouldn't the view start from the top so it shows the title first?

**Comment by JonasGessner** [comment]
No, but you can have it show the title first by commenting/removing this line: https://github.com/JonasGessner/JGActionSheet/blob/master/JGActionSheet/JGActionSheet.m#L696

**Comment by josher8** [comment]
Thanks!
