### ISSUE TITLE
Section Selection

### ISSUE THREAD

**Issue by toftof** [JonasGessner/JGActionSheet#12]
Hello, for multiple sections how to determine the section and the value that was clciked? Or selected? Thanks for your guidance.

**Comment by JonasGessner** [comment]
The example code <a href="https://github.com/JonasGessner/JGActionSheet#examples">here</a> uses the `buttonPressedBlock:`. That block has a NSIndexPath value which contains information on the row that was selected. Like in a UITableView, the index path contains section and row information.

**Comment by toftof** [comment]
Perfect and thank you.
