### ISSUE TITLE
Titles & Messages Retain

### ISSUE THREAD

**Issue by soulshined** [JonasGessner/JGActionSheet#15]
Having an issue with self retaining. 

Specifically the title and messages retain and i get the self - retaining cycle error when presenting from a UITableViewRowAction. 

I've followed the examples step by step but the title and messages retain. I've tried using __weak and __unsafe_unretained with the same results:

here tis the set up :

```
if (!actionSheet) {
    NSByteCountFormatter *sizeFormatter = [[NSByteCountFormatter alloc] init];
    sizeFormatter.countStyle = NSByteCountFormatterCountStyleFile;
    message = [NSString stringWithFormat:@"File size is %@", [sizeFormatter stringFromByteCount:filesize]]

    actionSheet = [[JGActionSheet alloc] initWithSections:@[[JGActionSheetSection sectionWithTitle:self.titleNum message:message buttonTitles:@[@"Export", @"Email"] buttonStyle:JGActionSheetButtonStyleDefault], [JGActionSheetSection sectionWithTitle:nil message:nil buttonTitles:@[@"Cancel"] buttonStyle:JGActionSheetButtonStyleCancel]]];

    actionSheet.delegate = self;

    actionSheet.insets = UIEdgeInsetsMake(20.0f, 0.0f, 0.0f, 0.0f);

    if (iPad) {
        [actionSheet setOutsidePressBlock:^(JGActionSheet *sheet) {
            [sheet dismissAnimated:YES];
        }];
    }

    __weak typeof(self) weakSelf = self;

    [actionSheet setButtonPressedBlock:^(JGActionSheet *sheet, NSIndexPath *indexPath) {
        [sheet dismissAnimated:YES];

        if (indexPath.section == 0 && indexPath.row == 0) {
            [weakSelf exportPublication];
        } else if (indexPath.section == 0 && indexPath.row == 1) {
            [weakSelf emailPublication];
        } else if (indexPath.section == 1 && indexPath.row == 0) {

        }
    }];

}

[actionSheet showInView:self.tabBarController.view animated:YES];
```

Every time i click on the UITableViewRowAction the title and message populate according to the cell but the next one i tap on it retains the first title and message I tapped on. All NSStrings have a weak property set.

**Comment by JonasGessner** [comment]
So basically the code you posted is taken from your UITableViewRowAction handler block? That last word is the key, that's a block. You already need a weak reference to self in that block, not just in the JGActionSheet callbacks. The whole thing also isn't related to this project at all, this is an incorrect implementation, not a bug in the project.
