### ISSUE TITLE
ActionSheet opens under TabBar

### ISSUE THREAD

**Issue by wasatchtechnology** [JonasGessner/JGActionSheet#2]
I have an application with a UITabBar and the ActionSheet opens under the TabBar.  
I tried [self.tabBarController.view bringSubviewToFront:sheet]; .
The ActionSheet isn't very modal at that time.

Thanks for the work!

**Comment by JonasGessner** [comment]
Ok so you're showing the action sheet in the UITabBarController's view?

**Comment by wasatchtechnology** [comment]
I'm bringing up the Action sheet from a TabBar event.  So the code to show
the ActionSheet is in my UIViewController.  I would assume the owner would
be the UIViewController.

Jon Clayton
jclayton@WasatchTech.com
WasatchTechnology@gmail.com
www.WasatchTech.com

**Comment by JonasGessner** [comment]
You need to present it in your UITabBarController's view. I've just tried that and as expected it works fine. Your UIViewController is nested inside the UITabBarController and obviously the UITabBar is over the UIViewController's view in the view hierarchy. And also, `[self.tabBarController.view bringSubviewToFront:sheet];` isn't going to do anything if the action sheet is not a subview of self.tabBarController.view. So, all you need to do is present the action sheet in self.tabBarController.view.
