### ISSUE TITLE
iOS9 action sheet behind keyboard

### ISSUE THREAD

**Issue by phaibin** [JonasGessner/JGActionSheet#22]
Under iOS9, when keyboard is showing, actionsheet will behind keyboard. Please fix this.

**Comment by phaibin** [comment]
?

**Comment by JonasGessner** [comment]
It's totally up to you where you show the action sheet. From a UI standpoint there is no sense in displaying an action sheet above a keyboard. If you still want to display the action sheet above a keyboard you have to show it in a new UIWindow with a higher window level than the keyboard (UIWindowLevelAlert probably).

**Comment by phaibin** [comment]
Understood, thanks!
