### ISSUE TITLE
Pin the Cancel button in the scrollview?

### ISSUE THREAD

**Issue by cujo30227** [JonasGessner/JGActionSheet#23]
Hi,
Excellent class! I have been playing around a bit with it, and was wondering if it is possible to pin the Cancel button to the bottom of the screen. When you have a long list with items and scroll up, the Cancel button (at the bottom of the list) scrolls off the screen. I would like it to stay at the bottom. I tried to add a separate UIView for this, but I couldn't get it to work..
Any thoughts?
Thanks!

**Comment by shitalsharma** [comment]
Hello,

Is it possible to pin cancel button at the bottom of screen and scrollview should be on top of uinavigationcontroller?

**Comment by sevy11** [comment]
Having an issue adding to the tableView
