### ISSUE TITLE
how to distinguish first button in action1 and cancen-action using indexPath

### ISSUE THREAD

**Issue by xiaohuli169** [JonasGessner/JGActionSheet#25]
[sheet setButtonPressedBlock:^(JGActionSheet *sheet, NSIndexPath *indexPath) {
    [sheet dismissAnimated:YES];
}];
I have two actions， action1 and cancel-action， how to distinguish first button in action1 and cancen-action using indexPath, because indexPath.row = 0

**Comment by JonasGessner** [comment]
indexPath.section

Please read the readme, look at the example project and read the documentation before opening an issue, it's all there.
