### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by xzenon** [JonasGessner/JGActionSheet#3]
Hi! This action sheet is amazing. But I have performance problems on my old iPhone 4 with iOS6 (while on 5S it runs smoothly of course). I use your example project to test and sheet scrolling is very laggy especially for sheet with several sections and many buttons. 
I tried to disable layer shadows but without a luck. 
Maybe you can advice how to increase performance? Thanks a lot!

**Comment by JonasGessner** [comment]
The performance is poor not only because of the shadow but also because of the rounded corners. So to improve the performance you could comment/remove the code that applies the corner radius and the shadow to the different CALayers.

**Comment by xzenon** [comment]
You're right, removing corners really makes difference in performance. Thanks again!
