### ISSUE TITLE
How do you detect which button is pressed?

### ISSUE THREAD

**Issue by deanezra** [JonasGessner/JGActionSheet#5]
Hi,

I noticed that the indexPath.row is always zero in the ButtonPressedBlock, how do I detect which button was pressed?

I notice your examples always do the same thing no matter what button is pressed:

 [_simple setButtonPressedBlock:^(JGActionSheet *sheet, NSIndexPath *indexPath) {
            [sheet dismissAnimated:YES];
        }];

PS Im using ios8 ipad

**Comment by JonasGessner** [comment]
indexPath.row is not always 0. It works like in a UITableView. indexPath.section determines the section and indexPath.row is the row in that section.

**Comment by deanezra** [comment]
Thanks for the hint of section. I had two sections both with only one button. So checking indexPath.row was always 0! Changing to check indexPath.section fixed it.
