### ISSUE TITLE
Wrong rotation size in iOS7

### ISSUE THREAD

**Issue by ghost** [JonasGessner/JGActionSheet#8]
If i present the shh like this 

[sheet showInView:AppDelegate.window animated:YES];

When i rotate the device it stays with a wrong size!

**Comment by JonasGessner** [comment]
Thats because UIWindows are not rotation aware and have a fixed size on iOS 7. Please read the Readme of UIActionSheet, it recommends to show an action sheet inside a UIViewController at all times.
